### ISSUE TITLE
2021 Roadmap

### ISSUE THREAD

**Issue by dineug** [vuerd/vuerd-vscode#113]
## TODO
- v2
  - [x] [Integrating with reactive system components](https://github.com/vuerd/vuerd/issues/181)
  - [x] [Extension Panel API](https://github.com/vuerd/vuerd/issues/182)
  - [x] [Zoom Level Support](https://github.com/vuerd/vuerd/issues/183)
- [x] Add options when creating SQL DDL
    - ex) Bracket
- [ ] generate template [#94](https://github.com/vuerd/vuerd-vscode/issues/94)
- [ ] chrome extension vuerd App
    - ex) ![vuerd App](https://user-images.githubusercontent.com/45829489/69156939-8c146b80-0b27-11ea-99ed-6f1b8ce3c3ae.gif)
